name: Scrape streams

on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install yt-dlp & curl
        run: |
          sudo apt update
          sudo apt install yt-dlp curl -y

      - name: Make script executable
        run: chmod +x scrape.sh

      - name: Run scraper
        run: bash scrape.sh

      - name: Commit outputs
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add outputs/*.m3u8
          git commit -m "Auto update streams" || echo "No changes"
          git push
